configuration: Publish
#image: Visual Studio 2017

environment:
  packageVersion: 1.4.1
  perfTestsPackageVersion: 0.1.4

cache:
# todo: remove after all csproj moved to the new tooling
- packages -> **\packages.config

init:
- cmd: git config --global core.autocrlf true
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion-alpha$env:appveyor_build_number"
- ps: $env:perfTestsBuildVersion = "$env:perfTestsPackageVersion.$env:appveyor_build_number"
- ps: $env:perfTestsNugetVersion = "$env:perfTestsPackageVersion-alpha$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'

dotnet_csproj:
  patch: true
  file: 'Build\CodeJam.Default.props'
  version: '$(buildVersion)'
  package_version: '$(nugetVersion)'

install:
- type Build\CodeJam.Default.props
- ps: sleep 20

build_script:
- type Build\CodeJam.Default.props
